fix: Remove unnecessary file and fix shell script in release.yml

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -22,6 +22,9 @@ jobs:
           elif [[ "$TAG_NAME" =~ ^development ]]; then
             BRANCH=development
           else
+            echo "Invalid tag name"
+            exit 1
+          fi
           VERSION=${TAG_NAME#$BRANCH-v}
 
           # Echo to the environment
